server:
  port: 14000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skill
    username: root
    password: jianjiang
  cloud:
    nacos:
      discovery:
        service: ad-serv
      server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
canal:
  server: 127.0.0.1:11111
  destination: example