server:
  port: 8081
spring:
  application:
    name: seata-at-storage
  # 数据源配置
  datasource:
    druid:
      url: jdbc:mysql://mysql.me:3306/seata_storage?allowMultiQueries=true
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: WJtEhgZYIEFYDCYo
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
# todo todo 步骤2：设置 seata 服务组名
# todo todo 步骤3：file.conf 中添加服务组名的映射