server:
  port: 8081
spring:
  application:
    name: service-consumer
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
