server:
  port: 8080
spring:
  application:
    name: dubbo-kryo-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
dubbo:
  registry:
    address: spring-cloud://localhost
  scan:
    base-packages: com.example.demo.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo