server:
  port: 8080
spring:
  application:
    name: service-zipkin
  sleuth:
    sampler: # todo 步骤2：设置 sleuth 的采样率
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411 # todo 步骤3：指定 zipkin 的连接地址
