server:
  port: 9090
spring:
  application:
    name: gateway-sentinel
  cloud:
    gateway:
      routes:
        - id: route-hi
          uri: http://localhost:8081/hi
          predicates:
            - Method=GET
        - id: route-product
          uri: http://localhost:8081
          predicates:
            - Path=/product/**
        - id: route-article
          uri: http://localhost:8081
          predicates:
            - Path=/article/**
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8890