server:
  port: 8083
spring:
  application:
    name: dubbo-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
dubbo:
  registry:
    address: spring-cloud://localhost
  scan:
    base-packages: com.example.demo.dubboservice
  protocol:
    name: dubbo
    port: -1
