server:
  port: 8080
spring:
  application:
    name: gateway-nacos
  cloud:
    gateway:
      routes:
        - id: route-test
          uri: http://localhost:8081/hi
          predicates:
            - Method=GET

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false