server:
  port: 8080
spring:
  application:
    name: gateway-predicate
  cloud:
    gateway:
      routes:
        - id: route-weight-v1
          uri: http://localhost:8001
          predicates:
            - Path=/test
            - Weight=service_weight,8
        - id: route-weight-v2
          uri: http://localhost:8002
          predicates:
            - Path=/test
            - Weight=service_weight,2

        - id: route-query
          uri: http://localhost:8081
          predicates:
            - Query=name, gree.
#        - id: route-path
#          uri: http://localhost:8081
#          predicates:
#            - Path=/users/{segment}
#        - id: route-header
#          uri: http://localhost:8081
#          predicates:
#            - Header=X-Request-Id, \d+
#        - id: route-cookie
#          uri: http://localhost:8081
#          predicates:
#            - Cookie=test, ch.p
#        - id: route-after
#          uri: http://localhost:8081
#          predicates:
#            - After=2020-04-21T09:32:33.314+08:00[Asia/Shanghai]