server:
  port: 8082
spring:
  application:
    name: dubbo-sentinel-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8890
dubbo:
  registry:
    address: spring-cloud://localhost
  scan:
    base-packages: com.example.demo.service
  protocol:
    name: dubbo
    port: -1

# todo 步骤2：添加 Sentinel 地址
