server:
  port: 8083
spring:
  application:
    name: score
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://server-base:3306/shop_score?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: HikariCP-Score
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: server-base:8848
logging:
  level:
    com.example.demo.mapper: debug

# todo [资源请求] 3. OAuth2 资源服务器配置
security:
  oauth2:
    client:
      client-id: client1
      client-secret: 123456
    resource:
      token-info-uri: http://server-app:9000/user/oauth/check_token