server:
  port: 8081
spring:
  application:
    name: dubbo-stub-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
dubbo:
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.example.demo.dubboservice