server:
  port: 8082
spring:
  application:
    name: service-provider
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
# todo [整合 micrometer] 步骤2：配置监控端点