server:
  port: 8080
spring:
  application:
    name: authserver-rbac
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://mysql.me:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: WJtEhgZYIEFYDCYo

# todo （配置 mybatis）步骤3：指定 mybatis 模型对象的包名
mybatis:
  type-aliases-package: com.example.demo.model